/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConditionComp: typeof import('./src/components/ConditionComp.vue')['default']
    OrganizationMembershipList: typeof import('./src/components/OrganizationMembershipList.vue')['default']
    PersonalAssetInput: typeof import('./src/components/PersonalAssetInput.vue')['default']
    PersonalAssetInputList: typeof import('./src/components/PersonalAssetInputList.vue')['default']
    ProvingTies: typeof import('./src/components/ProvingTies.vue')['default']
    RecursiveSchemaComp: typeof import('./src/components/RecursiveSchemaComp.vue')['default']
  }
}
