/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IcOutlineDarkMode: typeof import('~icons/ic/outline-dark-mode')['default']
    IcOutlineWbSunny: typeof import('~icons/ic/outline-wb-sunny')['default']
    OrganizationMembershipList: typeof import('./src/components/OrganizationMembershipList.vue')['default']
    PersonalAssetInputList: typeof import('./src/components/PersonalAssetInputList.vue')['default']
    RemoveBtn: typeof import('./src/components/RemoveBtn.vue')['default']
    TiesEvaluation: typeof import('./src/components/TiesEvaluation.vue')['default']
    TravelPlanList: typeof import('./src/components/TravelPlanList.vue')['default']
    WhenGeneralEligible: typeof import('./src/components/WhenGeneralEligible.vue')['default']
  }
}
